using Application.Models.GameServer.ConfigurationItem;
using Application.Models.GameServer.GameProfile;
using Application.Models.GameServer.GameServer;
using Application.Models.GameServer.LocalResource;
using Application.Models.GameServer.Mod;
using Application.Requests.GameServer.GameProfile;
using Application.Requests.GameServer.GameServer;
using Application.Requests.GameServer.LocalResource;
using Domain.Contracts;

namespace Application.Services.GameServer;

public interface IGameServerService
{
    Task<IResult<IEnumerable<GameServerSlim>>> GetAllAsync();
    Task<PaginatedResult<IEnumerable<GameServerSlim>>> GetAllPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetCountAsync();
    Task<IResult<GameServerSlim?>> GetByIdAsync(Guid id);
    Task<IResult<GameServerSlim?>> GetByServerNameAsync(string serverName);
    Task<IResult<IEnumerable<GameServerSlim>>> GetByGameIdAsync(Guid id);
    Task<IResult<GameServerSlim>> GetByGameProfileIdAsync(Guid id);
    Task<IResult<IEnumerable<GameServerSlim>>> GetByHostIdAsync(Guid id);
    Task<IResult<IEnumerable<GameServerSlim>>> GetByOwnerIdAsync(Guid id);
    Task<IResult<Guid>> CreateAsync(GameServerCreateRequest request, Guid requestUserId);
    Task<IResult> UpdateAsync(GameServerUpdateRequest request, Guid requestUserId);
    Task<IResult> DeleteAsync(Guid id, Guid requestUserId, bool sendHostUninstall = true);
    Task<IResult<IEnumerable<GameServerSlim>>> SearchAsync(string searchText);
    Task<PaginatedResult<IEnumerable<GameServerSlim>>> SearchPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<ConfigurationItemSlim>>> GetAllConfigurationItemsAsync();
    Task<PaginatedResult<IEnumerable<ConfigurationItemSlim>>> GetAllConfigurationItemsPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetConfigurationItemsCountAsync();
    Task<IResult<ConfigurationItemSlim>> GetConfigurationItemByIdAsync(Guid id);
    Task<IResult<IEnumerable<ConfigurationItemSlim>>> GetConfigurationItemsByLocalResourceIdAsync(Guid id);
    Task<IResult<Guid>> CreateConfigurationItemAsync(ConfigurationItemCreate request, Guid requestUserId);
    Task<IResult> UpdateConfigurationItemAsync(ConfigurationItemUpdate updateObject, Guid requestUserId);
    Task<IResult> DeleteConfigurationItemAsync(Guid id, Guid requestUserId);
    Task<IResult<IEnumerable<ConfigurationItemSlim>>> SearchConfigurationItemsAsync(string searchText);
    Task<PaginatedResult<IEnumerable<ConfigurationItemSlim>>> SearchConfigurationItemsPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<LocalResourceSlim>>> GetAllLocalResourcesAsync();
    Task<PaginatedResult<IEnumerable<LocalResourceSlim>>> GetAllLocalResourcesPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetLocalResourcesCountAsync();
    Task<IResult<LocalResourceSlim>> GetLocalResourceByIdAsync(Guid id);
    Task<IResult<IEnumerable<LocalResourceSlim>>> GetLocalResourcesByGameProfileIdAsync(Guid id);
    Task<IResult<IEnumerable<LocalResourceSlim>>> GetLocalResourcesForGameServerIdAsync(Guid id);
    Task<IResult<Guid>> CreateLocalResourceAsync(LocalResourceCreateRequest request, Guid requestUserId);
    Task<IResult> UpdateLocalResourceAsync(LocalResourceUpdateRequest request, Guid requestUserId);
    Task<IResult> DeleteLocalResourceAsync(Guid id, Guid requestUserId, bool sendUpdateToHost = false);
    Task<IResult> UpdateLocalResourceOnGameServerAsync(Guid serverId, Guid resourceId, Guid requestUserId);
    Task<IResult> UpdateAllLocalResourcesOnGameServerAsync(Guid serverId, Guid requestUserId);
    Task<IResult<IEnumerable<LocalResourceSlim>>> SearchLocalResourceAsync(string searchText);
    Task<PaginatedResult<IEnumerable<LocalResourceSlim>>> SearchLocalResourcePaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<GameProfileSlim>>> GetAllGameProfilesAsync();
    Task<PaginatedResult<IEnumerable<GameProfileSlim>>> GetAllGameProfilesPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetGameProfileCountAsync();
    Task<IResult<GameProfileSlim>> GetGameProfileByIdAsync(Guid id);
    Task<IResult<GameProfileSlim>> GetGameProfileByFriendlyNameAsync(string friendlyName);
    Task<IResult<IEnumerable<GameProfileSlim>>> GetGameProfilesByGameIdAsync(Guid id);
    Task<IResult<IEnumerable<GameProfileSlim>>> GetGameProfilesByOwnerIdAsync(Guid id);
    Task<IResult<Guid>> CreateGameProfileAsync(GameProfileCreateRequest request, Guid requestUserId);
    Task<IResult> UpdateGameProfileAsync(GameProfileUpdateRequest request, Guid requestUserId);
    Task<IResult> DeleteGameProfileAsync(Guid id, Guid requestUserId);
    Task<IResult<IEnumerable<GameProfileSlim>>> SearchGameProfilesAsync(string searchText);
    Task<PaginatedResult<IEnumerable<GameProfileSlim>>> SearchGameProfilesPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<ModSlim>>> GetAllModsAsync();
    Task<PaginatedResult<IEnumerable<ModSlim>>> GetAllModsPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetModCountAsync();
    Task<IResult<ModSlim>> GetModByIdAsync(Guid id);
    Task<IResult<ModSlim>> GetModByCurrentHashAsync(string hash);
    Task<IResult<IEnumerable<ModSlim>>> GetModsByFriendlyNameAsync(string friendlyName);
    Task<IResult<IEnumerable<ModSlim>>> GetModsByGameIdAsync(Guid id);
    Task<IResult<IEnumerable<ModSlim>>> GetModsBySteamGameIdAsync(int id);
    Task<IResult<ModSlim>> GetModBySteamIdAsync(string id);
    Task<IResult<IEnumerable<ModSlim>>> GetModsBySteamToolIdAsync(int id);
    Task<IResult<Guid>> CreateModAsync(ModCreate request, Guid requestUserId);
    Task<IResult> UpdateModAsync(ModUpdate request, Guid requestUserId);
    Task<IResult> DeleteModAsync(Guid id, Guid requestUserId);
    Task<IResult<IEnumerable<ModSlim>>> SearchModsAsync(string searchText);
    Task<PaginatedResult<IEnumerable<ModSlim>>> SearchModsPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult> StartServerAsync(Guid id, Guid requestUserId);
    Task<IResult> StopServerAsync(Guid id, Guid requestUserId);
    Task<IResult> RestartServerAsync(Guid id, Guid requestUserId);
    Task<IResult> UpdateServerAsync(Guid id, Guid requestUserId);
}