using Application.Models.GameServer.Host;
using Application.Models.GameServer.HostCheckIn;
using Application.Models.GameServer.HostRegistration;
using Application.Models.GameServer.WeaverWork;
using Application.Requests.GameServer.Host;
using Application.Requests.GameServer.WeaverWork;
using Application.Responses.v1.GameServer;
using Domain.Contracts;
using Domain.Enums.GameServer;

namespace Application.Services.GameServer;

public interface IHostService
{
    Task<IResult<HostNewRegisterResponse>> RegistrationGenerateNew(HostRegistrationCreateRequest request, Guid requestUserId);
    Task<IResult<HostRegisterResponse>> RegistrationConfirm(HostRegistrationConfirmRequest request, string registrationIp);
    Task<IResult<HostAuthResponse>> GetToken(HostAuthRequest request);
    Task<IResult> IsProvidedKeyCorrect(Guid hostId, string key);
    Task<IResult<IEnumerable<HostSlim>>> GetAllAsync();
    Task<PaginatedResult<IEnumerable<HostSlim>>> GetAllPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetCountAsync();
    Task<IResult<HostSlim?>> GetByIdAsync(Guid id);
    Task<IResult<HostSlim?>> GetByHostnameAsync(string hostName);
    Task<IResult<Guid>> CreateAsync(HostCreateRequest request, Guid requestUserId);
    Task<IResult> UpdateAsync(HostUpdateRequest request, Guid requestUserId);
    Task<IResult> DeleteAsync(Guid id, Guid requestUserId);
    Task<IResult<IEnumerable<HostSlim>>> SearchAsync(string searchText);
    Task<PaginatedResult<IEnumerable<HostSlim>>> SearchPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<HostRegistrationFull>>> GetAllRegistrationsAsync();
    Task<PaginatedResult<IEnumerable<HostRegistrationFull>>> GetAllRegistrationsPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<IEnumerable<HostRegistrationFull>>> GetAllActiveRegistrationsAsync();
    Task<IResult<IEnumerable<HostRegistrationFull>>> GetAllInActiveRegistrationsAsync();
    Task<IResult<int>> GetRegistrationCountAsync();
    Task<IResult<HostRegistrationFull>> GetRegistrationByIdAsync(Guid id);
    Task<IResult<HostRegistrationFull>> GetRegistrationByHostIdAsync(Guid hostId);
    Task<IResult> UpdateRegistrationAsync(HostRegistrationUpdateRequest request, Guid requestUserId);
    Task<IResult<int>> DeleteRegistrationsOlderThanAsync(Guid requestUserId, int olderThanHours = 24);
    Task<IResult<IEnumerable<HostRegistrationFull>>> SearchRegistrationsAsync(string searchText);
    Task<PaginatedResult<IEnumerable<HostRegistrationFull>>> SearchRegistrationsPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<HostCheckInFull>>> GetAllCheckInsAsync();
    Task<IResult<IEnumerable<HostCheckInFull>>> GetAllCheckInsAfterAsync(DateTime afterDate);
    Task<PaginatedResult<IEnumerable<HostCheckInFull>>> GetAllCheckInsPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetCheckInCountAsync();
    Task<IResult<HostCheckInFull>> GetCheckInByIdAsync(int id);
    Task<IResult<IEnumerable<HostCheckInFull>>> GetChecksInByHostIdAsync(Guid id);
    Task<IResult<IEnumerable<HostCheckInFull>>> GetCheckInsLatestByHostIdAsync(Guid id, int count = 10);
    Task<IResult> CreateCheckInAsync(HostCheckInCreate request);
    Task<IResult<int>> DeleteAllCheckInsForHostIdAsync(Guid id, Guid requestUserId);
    Task<IResult<int>> DeleteAllOldCheckInsAsync(DateTime olderThan, Guid requestUserId);
    Task<IResult<IEnumerable<HostCheckInFull>>> SearchCheckInsAsync(string searchText);
    Task<PaginatedResult<IEnumerable<HostCheckInFull>>> SearchCheckInsPaginatedAsync(string searchText, int pageNumber, int pageSize);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetAllWeaverWorkAsync();
    Task<PaginatedResult<IEnumerable<WeaverWorkSlim>>> GetAllWeaverWorkPaginatedAsync(int pageNumber, int pageSize);
    Task<IResult<int>> GetWeaverWorkCountAsync();
    Task<IResult<WeaverWorkSlim>> GetWeaverWorkByIdAsync(int id);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetWeaverWorkByHostIdAsync(Guid id);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetWeaverWaitingWorkByHostIdAsync(Guid id);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetWeaverAllWaitingWorkByHostIdAsync(Guid id);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetWeaverWorkByTargetTypeAsync(WeaverWorkTarget target);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetWeaverWorkByStatusAsync(WeaverWorkState status);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> GetWeaverWorkCreatedWithinAsync(DateTime from, DateTime until);
    Task<IResult<int>> CreateWeaverWorkAsync(WeaverWorkCreateRequest request, Guid requestUserId);
    Task<IResult> UpdateWeaverWorkAsync(WeaverWorkUpdate request, string sourceIp = "");
    Task<IResult> DeleteWeaverWorkAsync(int id, Guid requestUserId);
    Task<IResult> DeleteWeaverWorkForHostAsync(Guid hostId, Guid requestUserId);
    Task<IResult<int>> DeleteWeaverWorkOlderThanAsync(DateTime olderThan, Guid requestUserId);
    Task<IResult<IEnumerable<WeaverWorkSlim>>> SearchWeaverWorkAsync(string searchText);
    Task<PaginatedResult<IEnumerable<WeaverWorkSlim>>> SearchWeaverWorkPaginatedAsync(string searchText, int pageNumber, int pageSize);
}