namespace Domain.Enums.Lifecycle;

public enum AuditTableName
{
    Users = 0,
    Roles = 1,
    Permissions = 2,
    UserAttributes = 3,
    UserPreferences = 4,
    UserSecurity = 5,
    AuditTrails = 6,
    ServerStates = 7,
    AuthState = 13,
    Hosts = 14,
    HostRegistrations = 15,
    WeaverWorks = 16,
    GameGenres = 17,
    GameProfiles = 18,
    GameServers = 19,
    Developers = 20,
    Publishers = 21,
    Games = 22,
    LocalResources = 23,
    Mods = 24,
    ConfigurationItems = 25,
    TshootConfirmation = 500,
    TshootRegister = 501,
    TshootUsers = 502,
    TshootRoles = 503,
    TshootPermissions = 504,
    TshootGames = 505,
    TshootGameServers = 506,
    TshootLocalResources = 507,
    TshootHosts = 508,
    TshootGameProfiles = 509,
    TshootDevelopers = 510,
    TshootPublishers = 511,
    TshootConfigItems = 512,
    TshootGameGenres = 513,
    TshootGameUpdates = 514,
    TshootHostCheckins = 515,
    TshootHostRegistrations = 516,
    TshootMods = 517,
    TshootNetwork = 518,
    TshootWeaverWork = 519 
}